# Generated by Django 5.2.8 on 2025-11-18 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text="Student's answer")),
                ('score', models.DecimalField(decimal_places=1, default=0.0, help_text='Score out of 10', max_digits=3)),
                ('feedback', models.TextField(blank=True, help_text='AI-generated feedback')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='Teacher.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('question', 'student'), name='unique_student_question_answer')],
            },
        ),
    ]
