# Generated by Django 5.2.8 on 2025-11-18 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('Teacher', '0002_classroom_subject_assignment_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Upload your answer file (PDF, DOC, images)', null=True, upload_to='assignments/submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('answer_text', models.TextField(blank=True, help_text='Answer text (extracted from file or manually entered)')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score received', max_digits=5)),
                ('feedback', models.TextField(blank=True, help_text='AI-generated feedback')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('plagiarism', models.BooleanField(default=False, help_text='Plagiarism detected')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Teacher.assignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assignment',
                'verbose_name_plural': 'Student Assignments',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
